### PR TITLE
Misc enhancements

### PR DESCRIPTION
**Pull request by yazgoo**
Hi, thanks for this plugin.
Here are some changes I find usefull:

1. Allow to select glyphs based on `g:c98tabbar_kind` variable
2. print hour and battery
3. refresh tabbar every 30s (necessary for hour and battery)

### CODE REVIEW

**Comment by Kyuuhachi** [comment]
Huh, didn't expect other people to be using this.

Making the glyphs (and colors) configurable is a good idea. I don't think `kind` is the best name, though. I'll see if I can work something out.

I think showing the time and battery is a bit outside the scope of this plugin (especially since it adds a bunch of dependencies). I suggest you make a custom function that calls `C98TabLine()` and adds some extra stuff to the returned string, and set that to your `'tabline'`. (~~You might also want to add a `%=` before it to move that stuff to the right corner.~~ Seems you found that already.)

**Comment by yazgoo** [comment]
I added two variables:

- `let g:c98tabbar_redraw = 1` to redraw the statusline every 30s
- `let g:c98tabbar_additional_callback = 'TimeAndBattery'` to user define a callback for additional stuff, for example:
````ruby
function g:TimeAndBattery()
    let l:s = ' %= '
    let l:s .= system("date '+%Y-%m-%d %H:%M' | tr -d '\n'")
    let l:s .= ' '
    let l:s .= system("(which acpi 1>/dev/null 2>/dev/null && acpi || (which pmset 1>/dev/null 2>/dev/null && pmset -g batt))|grep -o '[0-9]*%'")
    let l:s .= '%%'
    return l:s
endfunction
````

**Comment by yazgoo** [comment]
Do you these `redraw` and `callback` functionalities can be merged ?
Maybe I can cleanup this PR a little bit ?

**Comment by Kyuuhachi** [comment]
I still don't think they really belong in this plugin, I'm afraid. For the extra status, I'd suggest you do `set tabline=%!C98TabLine().'%='.TimeAndBattery()`. As for the timer, that's only useful for a very small subset of users (not that the set of users is particularly large).

**Comment by yazgoo** [comment]
👌 thanks, I'll do that !

**Pull request closed without merging**
